project:
  type: website
  output-dir: "docs"

website:
  title: "Pawel R. Kulawiak"
  sidebar:
    logo: images/foto.png
  navbar:
    left:
      - href: index.qmd
        text: Forschung
      - Lebenslauf.qmd
      - Publikationen.qmd
      - OER.qmd
      - Kontakt.qmd
    right:
      - icon: github
        href: https://github.com/PawelKulawiak/
        aria-label: GitHub

format:
  html:
    lang: de
    theme: lux
    css: styles.css
    toc: true
    link-external-newwindow: true

nocite: |
  @*

