---
title: Forschung
bibliography: references.bib
csl: apa-cv.csl
---

Die gemeinsame Beschulung aller Schüler:innen im Zuge der Gestaltung eines inklusiven Bildungssystems ist eine zentrale Herausforderung der pädagogischen Praxis. Mein genuines Forschungsinteresse gilt dementsprechend den ***Gelingensbedingungen einer inklusiven Schule*** und somit dem Thema der ***Förderung und Teilhabe*** aller Schüler:innen an ***akademischen sowie sozialen Prozessen***. Meine Forschung fokussiert sich dabei insbesondere auf die Zielgruppe der ***Kinder und Jugendlichen mit Verhaltensauffälligkeiten (internalisierend/externalisierend)*** sowie auf ***Schüler:innen mit Epilepsie***.

Mit der Anwendung sowie Weiterentwicklung von Messmethoden, Forschungsdesigns und Analyseverfahren bin ich um eine differenzierte Wahrnehmung (Messung/Diagnostik), Untersuchung und Analyse der inklusions- und sonderpädagogischen Praxis bemüht. Somit möchte ich die Güte wissenschaftlicher Erkenntnisprozesse im Beriech der inklusions- und sonderpädagogischen Forschung anhand innovativer Forschungs- und Messmethoden maximieren. Mittels empirischer und theoretischer Arbeiten leiste ich daher einen Beitrag zur Weiterentwicklung inklusionspädagogischer und sonderpädagogischer Praxis.

## Ausgewählte Publikationen
